### ISSUE TITLE
Could you please apply a license?

### ISSUE THREAD

**Issue by heathermeeker** [izaakschroeder/semver-set#7]
MIT or BSD would be best. Thank you.

**Comment by voxpelli** [comment]
Very much 👍 on this @izaakschroeder, quite problematic to maintain a fork https://github.com/voxpelli/semver-set when I don't know the license of this code

**Comment by izaakschroeder** [comment]
Done! https://github.com/izaakschroeder/semver-set/pull/8

**Comment by izaakschroeder** [comment]
Published as `semver-set@0.1.2`.
